# Generated by Django 3.2.13 on 2022-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='slug',
        ),
    ]
