# Generated by Django 3.2.13 on 2022-05-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdvs', '0003_remove_rdv_email_organisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='image',
        ),
    ]
