# Generated by Django 3.2.13 on 2022-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdvs', '0004_remove_rdv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
