# Generated by Django 3.2.13 on 2022-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdvs', '0005_rdv_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='email_organisateur',
            field=models.EmailField(default='test@test.fr', max_length=254),
            preserve_default=False,
        ),
    ]
